// flow-typed signature: c57a31ff739fca352db78324c4ae8c10
// flow-typed version: <<STUB>>/@bedegaming/spine-player-client-js_v^0.4.3/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@bedegaming/spine-player-client-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@bedegaming/spine-player-client-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@bedegaming/spine-player-client-js/src/api' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/src/util' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/activities' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/authentication' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/balances' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/bonuses' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/deposit' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/games' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/headers' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/limits' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/loyalty' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/messages' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/payment-entities' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/ping' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/player' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/promotions' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/requests' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/utils' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/wallets' {
  declare module.exports: any;
}

declare module '@bedegaming/spine-player-client-js/test/withdrawal' {
  declare module.exports: any;
}

// Filename aliases
declare module '@bedegaming/spine-player-client-js/src/api.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/src/api'>;
}
declare module '@bedegaming/spine-player-client-js/src/util.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/src/util'>;
}
declare module '@bedegaming/spine-player-client-js/test/activities.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/activities'>;
}
declare module '@bedegaming/spine-player-client-js/test/authentication.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/authentication'>;
}
declare module '@bedegaming/spine-player-client-js/test/balances.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/balances'>;
}
declare module '@bedegaming/spine-player-client-js/test/bonuses.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/bonuses'>;
}
declare module '@bedegaming/spine-player-client-js/test/deposit.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/deposit'>;
}
declare module '@bedegaming/spine-player-client-js/test/games.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/games'>;
}
declare module '@bedegaming/spine-player-client-js/test/headers.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/headers'>;
}
declare module '@bedegaming/spine-player-client-js/test/limits.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/limits'>;
}
declare module '@bedegaming/spine-player-client-js/test/loyalty.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/loyalty'>;
}
declare module '@bedegaming/spine-player-client-js/test/messages.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/messages'>;
}
declare module '@bedegaming/spine-player-client-js/test/payment-entities.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/payment-entities'>;
}
declare module '@bedegaming/spine-player-client-js/test/ping.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/ping'>;
}
declare module '@bedegaming/spine-player-client-js/test/player.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/player'>;
}
declare module '@bedegaming/spine-player-client-js/test/promotions.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/promotions'>;
}
declare module '@bedegaming/spine-player-client-js/test/requests.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/requests'>;
}
declare module '@bedegaming/spine-player-client-js/test/utils.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/utils'>;
}
declare module '@bedegaming/spine-player-client-js/test/wallets.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/wallets'>;
}
declare module '@bedegaming/spine-player-client-js/test/withdrawal.js' {
  declare module.exports: $Exports<'@bedegaming/spine-player-client-js/test/withdrawal'>;
}
