// flow-typed signature: b73e0d60a70dd3ee8c46f253ba02c5df
// flow-typed version: <<STUB>>/js-yaml-loader_v^1.0.1/flow_v0.84.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'js-yaml-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'js-yaml-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'js-yaml-loader/index' {
  declare module.exports: $Exports<'js-yaml-loader'>;
}
declare module 'js-yaml-loader/index.js' {
  declare module.exports: $Exports<'js-yaml-loader'>;
}
